

- name: Remove service
  win_service:
    name: winlogbeat
    state: absent

- name: Remove any previous winlogbeat
  win_file:
    path: "{{ winlogbeat_extract_location }}"
    state: absent

- name: Recreate directory
  win_file:
    path: "{{ winlogbeat_extract_location }}"
    state: directory


- name: Get winlogbeat zip
  win_get_url:
    url: "{{ winlogbeat_download_url_base }}/{{ winlogbeat_download_file }}{{ file_ext }}"
    dest: "{{ winlogbeat_extract_location }}/{{ winlogbeat_download_file }}{{ file_ext }}"
  when: winlogbeat_install_offline is false

- name: Get winlogbeat zip (offline)
  win_copy:
     src: "{{ winlogbeat_offline_file }}{{ file_ext }}"
     dest: "{{ winlogbeat_extract_location }}/{{ winlogbeat_download_file }}{{ file_ext }}"
  when: winlogbeat_install_offline is true

- name: Unzip winlogbeat
  win_unzip:
    src: "{{ winlogbeat_extract_location }}/{{ winlogbeat_download_file }}{{ file_ext }}"
    dest: "{{ winlogbeat_extract_location }}"
#  when: winlogbeat_install_offline is true

- name: Install the service via script
  win_command: powershell.exe -ExecutionPolicy ByPass -File "{{ winlogbeat_install_location }}/install-service-winlogbeat.ps1"
  args:
    chdir: "{{ winlogbeat_install_location }}"

- name: Add WECSVC as dependency
  win_service:
    name: winlogbeat
    dependencies:
      - wecsvc
